# cassandra only

services:
  cassandra:
    container_name: cassandra
    image: cassandra:4.1.4
    # build: ./db/
    restart: always
    environment:
      - CASSANDRA_USER=admin
      - CASSANDRA_PASSWORD=admin
      - CASSANDRA_CLUSTER_NAME=main
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    ports:
      - 9042:9042
    volumes:
      - ./db/data:/var/lib/cassandra
      
  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    image: cassandra:4.1.4
    depends_on:
      - cassandra
    volumes:
      - ./db/schema.cql:/schema.cql 
    command: /bin/bash -c "sleep 60 && echo loading cassandra keyspace && cqlsh cassandra -f /schema.cql"
      
volumes:
  cassandra_db: 