services:
  frontend:
    container_name: webapp
    build: ./webapp/
    ports:
      - 80:8088
    environment:
      # - NEXT_TELEMETRY_DISABLED=1
      - NODE_ENV=development
    # depends_on:
    #   - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

  backend:
    container_name: backend
    build:
      context: ./backend/
      network: host
    restart: always
    ports:
      - 9099:9099
    environment:
      - RUST_BACKTRACE=1
      - DATABASE_URL=postgres://niooi:abcde@127.0.0.1:9432/postgres
    depends_on:
      - db

  db:
    container_name: db
    image: cassandra:4.1.4
    restart: always
    environment:
      - CASSANDRA_USER=admin
      - CASSANDRA_PASSWORD=admin
      - CASSANDRA_CLUSTER_NAME=main
    ports:
      - 9042:9042
    volumes:
      - cassandra_db:/var/lib/cassandra
      
volumes:
  cassandra_db: 